"""Add updated timestamp and indexes to absencs table

Revision ID: 6ae196b0dfce
Revises: 716b963e00c2
Create Date: 2025-09-23 13:23:58.775576

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ae196b0dfce"
down_revision: Union[str, Sequence[str], None] = "716b963e00c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "absences",
        sa.Column(
            "updated", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.create_index(
        "ix_absence_employee_dates",
        "absences",
        ["employee_id", "start_date", "end_date"],
        unique=False,
    )
    op.create_index("ix_absence_employee_id", "absences", ["employee_id"], unique=False)
    op.create_index("ix_absence_end_date", "absences", ["end_date"], unique=False)
    op.create_index("ix_absence_start_date", "absences", ["start_date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_absence_start_date", table_name="absences")
    op.drop_index("ix_absence_end_date", table_name="absences")
    op.drop_index("ix_absence_employee_id", table_name="absences")
    op.drop_index("ix_absence_employee_dates", table_name="absences")
    op.drop_column("absences", "updated")
    # ### end Alembic commands ###
