"""Add primary keys to Token, Employee, and Schedule tables

Revision ID: 716b963e00c2
Revises: fdf4dcd12833
Create Date: 2025-09-23 12:46:34.455052

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "716b963e00c2"
down_revision: Union[str, Sequence[str], None] = "fdf4dcd12833"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
