"""Final model updates - primary keys, timestamps, indexes

Revision ID: 731ba0d68488
Revises: 6ae196b0dfce
Create Date: 2025-09-23 14:17:34.543135

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "731ba0d68488"
down_revision: Union[str, Sequence[str], None] = "6ae196b0dfce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
