"""Add indexes to measures table

Revision ID: 9edaeb571eaf
Revises: b8dc0bfad124
Create Date: 2025-09-22 09:01:34.647638

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9edaeb571eaf"
down_revision: Union[str, Sequence[str], None] = "b8dc0bfad124"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_measure_active_time", "measures", ["is_active", "time_of_day"], unique=False
    )
    op.create_index("ix_measure_is_active", "measures", ["is_active"], unique=False)
    op.create_index("ix_measure_is_standard", "measures", ["is_standard"], unique=False)
    op.create_index(
        "ix_measure_time_flexibility", "measures", ["time_flexibility"], unique=False
    )
    op.create_index("ix_measure_time_of_day", "measures", ["time_of_day"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_measure_time_of_day", table_name="measures")
    op.drop_index("ix_measure_time_flexibility", table_name="measures")
    op.drop_index("ix_measure_is_standard", table_name="measures")
    op.drop_index("ix_measure_is_active", table_name="measures")
    op.drop_index("ix_measure_active_time", table_name="measures")
    # ### end Alembic commands ###
