"""update customer_measures with frequency fields

Revision ID: b8dc0bfad124
Revises: ef0ebc1d24ba
Create Date: 2025-09-18 13:02:39.085355

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b8dc0bfad124"
down_revision: Union[str, Sequence[str], None] = "ef0ebc1d24ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customer_measures",
        sa.Column("frequency", sa.String(length=50), nullable=False),
    )
    op.add_column(
        "customer_measures", sa.Column("days_of_week", sa.JSON(), nullable=True)
    )
    op.add_column(
        "customer_measures",
        sa.Column("occurrences_per_week", sa.Integer(), nullable=True),
    )
    op.drop_column("customer_measures", "customer_frequency")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customer_measures",
        sa.Column(
            "customer_frequency",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("customer_measures", "occurrences_per_week")
    op.drop_column("customer_measures", "days_of_week")
    op.drop_column("customer_measures", "frequency")
    # ### end Alembic commands ###
