"""add customer_id to care_visits

Revision ID: c69761829f83
Revises: 53e92650880d
Create Date: 2025-09-18 11:03:02.569596

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c69761829f83"
down_revision: Union[str, Sequence[str], None] = "53e92650880d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("care_visits", sa.Column("customer_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        "fk_care_visits_customer_id",
        "care_visits",
        "customers",
        ["customer_id"],
        ["id"],
    )
    op.add_column("measures", sa.Column("is_standard", sa.Boolean(), nullable=False))
    op.add_column("measures", sa.Column("is_active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("measures", "is_active")
    op.drop_column("measures", "is_standard")
    op.drop_constraint("fk_care_visits_customer_id", "care_visits", type_="foreignkey")
    op.drop_column("care_visits", "customer_id")
    # ### end Alembic commands ###
