"""add fk name to care_visits

Revision ID: ef0ebc1d24ba
Revises: c69761829f83
Create Date: 2025-09-18 11:10:16.511426

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "ef0ebc1d24ba"
down_revision: Union[str, Sequence[str], None] = "c69761829f83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
