"""Add indexes to care_visits table

Revision ID: fdf4dcd12833
Revises: 9edaeb571eaf
Create Date: 2025-09-22 21:58:46.700010

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fdf4dcd12833"
down_revision: Union[str, Sequence[str], None] = "9edaeb571eaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("care_visits", sa.Column("updated", sa.DateTime(), nullable=False))
    op.create_index(
        "ix_care_visit_customer_date",
        "care_visits",
        ["customer_id", "date"],
        unique=False,
    )
    op.create_index(
        "ix_care_visit_customer_id", "care_visits", ["customer_id"], unique=False
    )
    op.create_index("ix_care_visit_date", "care_visits", ["date"], unique=False)
    op.create_index(
        "ix_care_visit_schedule_date",
        "care_visits",
        ["schedule_id", "date"],
        unique=False,
    )
    op.create_index(
        "ix_care_visit_schedule_id", "care_visits", ["schedule_id"], unique=False
    )
    op.create_index("ix_care_visit_status", "care_visits", ["status"], unique=False)
    op.create_index(
        "ix_care_visit_status_date", "care_visits", ["status", "date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_care_visit_status_date", table_name="care_visits")
    op.drop_index("ix_care_visit_status", table_name="care_visits")
    op.drop_index("ix_care_visit_schedule_id", table_name="care_visits")
    op.drop_index("ix_care_visit_schedule_date", table_name="care_visits")
    op.drop_index("ix_care_visit_date", table_name="care_visits")
    op.drop_index("ix_care_visit_customer_id", table_name="care_visits")
    op.drop_index("ix_care_visit_customer_date", table_name="care_visits")
    op.drop_column("care_visits", "updated")
    # ### end Alembic commands ###
